### PR TITLE
Add ability to keep the generated example tests after test suite finishes

### PR DESCRIPTION
**Pull request by paulfioravanti**
Currently, the Elm tests that `elm-verify-examples` generates are deleted by default once the test suite finishes running. 

This means that it's not possible to include those tests (and hence the verified examples) when attempting to determine the code coverage of an app using a tool like [`elm-coverage`](https://github.com/zwilias/elm-coverage).

While respecting that the current default _is_ to delete those example tests, this PR seeks to provide the option to keep them around for those who would like to.

### CODE REVIEW

**Comment by stoeffel** [comment]
hmmm.. will think about this. I actually think this shouldn't be counted into coverage, since this shouldn't be used as a replacement for tests.

**Comment by paulfioravanti** [comment]
Totally understand. If the project stance is that verified examples should only ever be ephemeral, and that providing options to keep them around would be encouraging undesirable testing practices, then I'm happy to have this issue closed.

I admit I've been using verified examples in the same way I would Elixir doctests: if what I would write in the verified example would be exactly the same as what I'd write in a test file, then I figured I'd avoid the duplication (hence the reason for the PR).

**Comment by stoeffel** [comment]
oh sorry. I totally forgot about this will pr. Will make a decision this week. Thanks for your contribution.

**Comment by stoeffel** [comment]
> Totally understand. If the project stance is that verified examples should only ever be ephemeral, and that providing options to keep them around would be encouraging undesirable testing practices, then I'm happy to have this issue closed.

I think I'm still on the side of not wanting to include this argument, because I don't think we should use this tool to write tests, but to write better documentation. I hope it's okay if I'm going to close this for now. Thanks for using the tool and thinking about improvements.

**Pull request closed without merging**
